name: Deploy

concurrency:
  group: deploy-${{github.ref}}
  cancel-in-progress: true

on:
  push: 
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3.1.0
        with:
          push: true
          context: ./
          tags: buckhamduffy/cloudflared:latest